[package]
name = "dmmt-jpeg-encoder"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[[bin]]
name="sheet2-1"
path="src/sheet2_1.rs"

[[bin]]
name="dmmt-jpeg-encoder"
path="src/main.rs"

[dependencies]
